### ISSUE TITLE
Error displaying gifti object

### ISSUE THREAD

**Issue by bmdeen** [gllmflndn/gifti#7]
I'm getting the below errors when trying to display a loaded gifti object:

<img width="513" alt="Screen Shot 2020-12-24 at 12 10 19 PM" src="https://user-images.githubusercontent.com/25968062/103100694-c2050880-45e1-11eb-8756-5a9912b5b8fb.png">

I'm running MATLAB 2020b on Mac OS 10.15.7. The surface data itself is read properly, and I can plot the surface or display g.vertices and g.faces without error; displaying g.mat gives a similar error. Any idea what's going wrong? Thanks,

Ben

**Comment by gllmflndn** [comment]
Hi @bmdeen 
I think I have seen this before and it was due to files that were actually not compliant with the GIfTI standard.
I ended up having two diverging implementations and I might have added a workaround for only one implementation. Could you check what happens if using `@gifti` from SPM12:
https://github.com/spm/spm12/tree/master/%40gifti
If it doesn't solve the issue, it would be great if you could share with me a example of a GIfTI file so that I can reproduce the issue. I will anyway try to merge the two GIfTI libraries.

**Comment by bmdeen** [comment]
Hi Guillaume,

I don't get this error with the SPM implementation. The file I was loading was produced directly by mris_convert and didn't have a structure specified; when I add a structure, the error is resolved. Thanks for your help,

Ben
